version: "3"
services:
  app:
    image: kotlin-ktor-server:latest
    networks:
      - net
    environment:
      - "MY_VAR=${MY_VAR}"
    command: sh scripts/start.sh
    ports:
      - 30000:8000
networks:
  net:

